### ISSUE TITLE
issue with configuring plug in for android 

### ISSUE THREAD

**Issue by sivasethusaravanans** [DeepARSDK/deepar-flutter-plugin#19]
We have try to follow the instructions for android setup mentioned here - https://github.com/DeepARSDK/deepar-flutter-plugin

We are getting an error -

Execution failed for task ':deepar_flutter:generateDebugRFile'.
> Could not resolve all files for configuration ':deepar_flutter:debugCompileClasspath'.
   > Could not find :deepar:.
     Required by:
         project :deepar_flutter

let us know there are any fixes for this.

**Comment by mohamedsalah414** [comment]
Android: Please download the native android dependencies from our [downloads](https://developer.deepar.ai/downloads) section and save it at two locations:

In your flutter project as `android/app/libs/deepar.aar`.
In the root of your flutter environment directory, navigate to deepar_flutter [pub-cache folder](https://dart.dev/tools/pub/cmd/pub-get#the-system-package-cache) and create a new `libs` folder and place the `deepar.aar` file as following:
`~/.pub-cache/hosted/pub.dartlang.org/deepar_flutter-<plugin-version>/android/libs/deepar.aar` (Linux/ Mac)
`%LOCALAPPDATA%\Pub\Cache\hosted\pub.dartlang.org\deepar_flutter-<plugin-version>\android\libs\deepar.aar` (Windows)

**Comment by sivasethusaravanans** [comment]
we have saved deepar.aar file in both the locations android/app/libs and AppData\Local\Pub\Cache\hosted\pub.dartlang.org\deepar_flutter-0.0.1\android\libs (do note that this path is slightly different as it uses AppData instead of LOCALAPPDATA on a Windows 10 laptop)
with this setup the issue still persists.

**Comment by github-harsh-kashyap** [comment]
You have to paste **deepar.aar** file into 2 different folders :-
 1. In your flutter project as **android/app/libs/deepar.aar.**
 2. %LOCALAPPDATA%\Pub\Cache\hosted\pub.dartlang.org\deepar_flutter-<plugin-version>\android\libs\deepar.aar

**Comment by bachras** [comment]
@github-harsh-kashyap followed your instructions but still have the same problem.

**Comment by github-harsh-kashyap** [comment]
@bachras What is the gradle version you are using ? 
  try using this version in your **android/build.gradle**

dependencies {

        classpath 'com.android.tools.build:gradle:3.5.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}
and if still error exists try updating your android studio version.

**Comment by naveed61991** [comment]
> 1. run flutter clean
> 2. delete pubspec.lock
> 3. run flutter pub cache clean
> 
> then try to do this :-
> 
> 1. You have to paste **deepar.aar** file into 2 different folders :-
>    a. First In your flutter project as **android/app/libs/deepar.aar.**
>    b. Second ### %LOCALAPPDATA%\Pub\Cache\hosted\pub.dartlang.org\deepar_flutter-\android\libs\deepar.aar
> 2. in Build.gradle
> 
> defaultConfig { minSdkVersion 24 compileSdkVersion 33 }
> 
> 3. proguard-rules.pro
> 
> -keepclassmembers class ai.deepar.ar.DeepAR { _; } -keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava { _; } -keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava -dontwarn android.__ -keep class io.flutter.app.** { _; } -keep class io.flutter.plugin._* { _; } -keep class io.flutter.util._* { _; } -keep class io.flutter.view._* { _; } -keep class io.flutter._* { _; } -keep class io.flutter.plugins._* { *; }

After this I get a new error

The installation of android version fails compilation with below error:

FAILURE: Build failed with an exception.

Where:
Build file 'C:\Flutter Apps\ar_filters_app\android\app\build.gradle' line: 28

What went wrong:
A problem occurred evaluating project ':app'.

No signature of method: build_724lciaupkxaio6jex3xsvws6.android() is applicable for argument types: (build_724lciaupkxaio6jex3xsvws6$_run_closure2) values: [build_724lciaupkxaio6jex3xsvws6$_run_closure2@359cf42d]

pls help

**Comment by naveed61991** [comment]
> 

After downgrading gradle version i get this error

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':deepar_flutter:compileDebugAidl'.

**Comment by sarfbooztahera** [comment]
Any timeline when the installation issues will be fixed?

**Comment by tarekmabdallah91** [comment]
faced the same issue, waiting the solution.

**Comment by omflutteromninos** [comment]
same issue and waiting for fix any idea when it will be fixed?

**Comment by omflutteromninos** [comment]
so finally after struggling a lot I found a solution
so simply go to  external library folders available at the bottom and then go to dart packages and find deep ar folder and open this folder in explorer if you are using windows or open this folder in finder if you are Mac.
and then find the android folder here and paste lib/deep.aar file here everything will work than
have a great day

**Comment by DanteAlucard98** [comment]
@omflutteromninos Could you explain again please?  i dont understand your solution

**Comment by alkaou** [comment]
Hello everyone, I just spent a whole day implementing DeepAR in my flutter application, I followed all your instructions but still got errors. Can you help me please. I will be very happy.

`* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform deepar-.aar (:deepar:) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar.
         > /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar/AndroidManifest.xml
   > Failed to transform deepar-.aar (:deepar:) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar.
         > /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s
Running Gradle task 'assembleDebug'...                            137,0s
Exception: Gradle task assembleDebug failed with exit code 1`
