### ISSUE TITLE
Issue configuring plugin for iOS

### ISSUE THREAD

**Issue by bjmcallister** [DeepARSDK/deepar-flutter-plugin#20]
We have tried to follow the instructions for iOS setup mentioned here - https://github.com/DeepARSDK/deepar-flutter-plugin

No such module 'DeepAR'

I noticed in "Copy the DeepAR.xcframework file from /lib folder of the downloaded file and paste as /ios/DeepAR.xcframework in the plugin's directory. Please use the pub-cache folder reference as mentioned in android section." There is a folder called DeepAR.xcframework, but no file. I tried it with the folder to no success.

**Comment by sunil3590** [comment]
Hi @bjmcallister , I have the same issue. Were you able to fix this?
