### ISSUE TITLE
Improve installation process of native dependencies.

### ISSUE THREAD

**Issue by wilson-christian** [DeepARSDK/deepar-flutter-plugin#23]

**Comment by naveed61991** [comment]
Is there an ETA for this? The installation of android version fails compilation with below error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Flutter Apps\ar_filters_app\android\app\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_724lciaupkxaio6jex3xsvws6.android() is applicable for argument types: (build_724lciaupkxaio6jex3xsvws6$_run_closure2) values: [build_724lciaupkxaio6jex3xsvws6$_run_closure2@359cf42d]

**Comment by sivasethusaravanans** [comment]
Please let us know by when this will be available .

**Comment by wilson-christian** [comment]
We have simplified the process in `0.0.4` Please update to latest plugin.
