### ISSUE TITLE
Implement SDK pre-installed in the package

### ISSUE THREAD

**Issue by J4ckSk3le7on** [DeepARSDK/deepar-flutter-plugin#24]
Hi! When I say 'implement SDK pre-installed in the package' I mean not having to go through the process of installing the Android and iOS SDK in the Flutter package cache, because some of us use platforms like Codemagic, which do not allow manipulation of the cache.

**Comment by J4ckSk3le7on** [comment]
After forking the project and making some changes it is now working correctly, would you like me to leave you a PR?

**Comment by wilson-christian** [comment]
Our initial thought was to provide SDK pre-installed but it doesn't align with our goal of letting the devs use latest SDK from our website & use it.

**Comment by wilson-christian** [comment]
@J4ckSk3le7on Yes please add an PR we might consider it for now. Thanks
