### ISSUE TITLE
Masks do not work on Android

### ISSUE THREAD

**Issue by J4ckSk3le7on** [DeepARSDK/deepar-flutter-plugin#28]
Hi! I have purchased a pack of Beauty Masks but these only work on iOS, Not on Android.

Any idea how I can get it to work?

**Comment by J4ckSk3le7on** [comment]
For DeepAR equipment, this happens to me specifically with the Beauty Lite package.

**Comment by JoergPf** [comment]
Same here, the camera preview with the DeepAR.ai logo is available on Android, but it doesn't show the aviators mask on Android after calling switchMask. On iOS everything is working fine.

`
   void _switchMask() {
       debugPrint('_switchMask');
       _controller.switchFaceMask('assets/masks/aviators');
     }
`

This is my error log from the Debugging Console:


- ....
- `I/flutter (31208): assets/masks/aviators
- D/DEEPAR_LOGS(31208): licenseKey = 12345
- I/WebViewFactory(31208): Loading com.google.android.webview version 104.0.5112.97 (code 511209733)
- W/2.souvenirklub(31208): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
- W/2.souvenirklub(31208): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
- W/2.souvenirklub(31208): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
- W/2.souvenirklub(31208): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
- W/2.souvenirklub(31208): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
- I/cr_WVCFactoryProvider(31208): Loaded version=104.0.5112.97 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
- I/cr_LibraryLoader(31208): Successfully loaded native library
- I/cr_CachingUmaRecorder(31208): Flushed 9 samples from 9 histograms.
- W/Looper  (31208): Looper already prepared for this thread with a different value for the LOOPER_PREPARE_ALLOW_NON_CALLBACKS option.
- E/Looper  (31208): Invalid attempt to set NULL callback but not allowed for this looper.
- D/CameraRepository(31208): Added camera: 0
- I/Camera2CameraInfo(31208): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
- D/CameraRepository(31208): Added camera: 1
- D/UseCaseAttachState(31208): Active and attached use case: [] for camera: 0
- I/Camera2CameraInfo(31208): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
- D/UseCaseAttachState(31208): Active and attached use case: [] for camera: 1
- D/CameraOrientationUtil(31208): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
- I/chatty  (31208): uid=10202(com.ht22.bla) identical 1 line
- D/CameraOrientationUtil(31208): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
- D/DeferrableSurface(31208): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@252bad8}
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Use case ImageAnalysis:androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be98 ACTIVE
- D/UseCaseAttachState(31208): Active and attached use case: [] for camera: 1
- I/flutter (31208): value
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Use cases [ImageAnalysis:androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be98] now ATTACHED
- I/flutter (31208): then value: true
- I/flutter (31208): deepAr initialized?
- I/flutter (31208): true
- D/UseCaseAttachState(31208): All use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- D/UseCaseAttachState(31208): Active and attached use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- D/DEEPAR_LOGS(31208): initialized : DEEPAR
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Resetting Capture Session
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Releasing session in state INITIALIZED
- D/CameraStateRegistry(31208): tryOpenCamera(Camera@1f3938d[id=1]) [Available Cameras: 1, Already Open: false (Previous state: null)] --> SUCCESS
- D/CameraStateRegistry(31208): Recalculating open cameras:
- D/CameraStateRegistry(31208): Camera                                       State
- D/CameraStateRegistry(31208): -------------------------------------------------------------------
- D/CameraStateRegistry(31208): Camera@2ce1ddb[id=0]                         UNKNOWN
- D/CameraStateRegistry(31208): Camera@1f3938d[id=1]                         OPENING
- D/CameraStateRegistry(31208): -------------------------------------------------------------------
- D/CameraStateRegistry(31208): Open count: 1 (Max allowed: 1)
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Transitioning camera internal state: INITIALIZED --> OPENING
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Opening camera.
- D/UseCaseAttachState(31208): All use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- W/Gralloc4(31208): allocator 3.x is not supported
- W/Gralloc3(31208): allocator 3.x is not supported
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Use case ImageAnalysis:androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be98 ACTIVE
- D/UseCaseAttachState(31208): Active and attached use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} CameraDevice.onOpened()
- D/Camera2CameraImpl(31208): {Camera@1f3938d[id=1]} Transitioning camera internal state: OPENING --> OPENED
- D/CameraStateRegistry(31208): Recalculating open cameras:
- D/CameraStateRegistry(31208): Camera                                       State
- D/CameraStateRegistry(31208): -------------------------------------------------------------------
- D/CameraStateRegistry(31208): Camera@2ce1ddb[id=0]                         UNKNOWN
- D/CameraStateRegistry(31208): Camera@1f3938d[id=1]                         OPEN
- D/CameraStateRegistry(31208): -------------------------------------------------------------------
- D/CameraStateRegistry(31208): Open count: 1 (Max allowed: 1)
- D/UseCaseAttachState(31208): All use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- D/UseCaseAttachState(31208): Active and attached use case: [androidx.camera.core.ImageAnalysis-6c368242-63c5-491c-87dd-fb0f0c67be985164012] for camera: 1
- D/SyncCaptureSessionBase(31208): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@d68a08] getSurface...done
- D/DeferrableSurface(31208): New surface in use[total_surfaces=1, used_surfaces=1](androidx.camera.core.impl.ImmediateSurface@252bad8}
- D/DeferrableSurface(31208): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@252bad8
- D/CaptureSession(31208): Opening capture session.
- D/CaptureSession(31208): Attempting to send capture request onConfigured
- D/CaptureSession(31208): Issuing request for session.
- D/CaptureSession(31208): CameraCaptureSession.onConfigured() mState=OPENED
- D/CaptureSession(31208): CameraCaptureSession.onReady() OPENED
- I/flutter (31208): _switchMask

`

**Comment by github-harsh-kashyap** [comment]
> 

Please check if aviator mask is exists in this 'assets/masks/' directory or not . if not then you can manually put a mask of '.deepar' extension in this directory.

**Comment by JoergPf** [comment]
Thanks for your answer.

I have the masks available at assets/masks/ and renamed them that they have the .deepar suffix now. 
But unfortunately it still doesn't work on Android. It works fine on iOS.

This is my flutter doctor -v:

✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale de-DE)
    • Flutter version 3.0.5 at /Users/bla/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (vor 7 Wochen), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/bla/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Pixel 2 XL (mobile)   • 11111            • android-arm64  • Android 11 (API 30)
    • Iphone 12 (mobile) • 1111 • ios            • iOS 15.6 19G71
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by github-harsh-kashyap** [comment]
@JoergPf 

Only aviator is not working or other masks are also not working ?

 if aviator is not working then : 
Go to official site and login ' https://www.deepar.ai/ ' then find the free mask from here **Demo project > Flutter Quickstart Example scroll to bottom** or download the free masks from here [https://sdk.developer.deepar.ai/examples/free_package.zip](url) . Try adding new masks if only aviator is not working.

If other masks are not working : 

1. Then try cleaning cache 
2. check all permissions
3. uninstall the app from device/emulator and re-run the project.

if  still these above solution not works then please re-check the android guide.

**Comment by JoergPf** [comment]
Thanks for your help, the viking_helmet.deepar mask from the free examples is working now! 

Still it is very picky to load on my Pixel 2XL, I have to move a lot the mobile phone and cover the camera with my hand for a sec until it recognizes my head and puts on the helmet.

Is this a performance issue?

**Comment by J4ckSk3le7on** [comment]
Hi, I still can't use the filters in Android, no error message or anything like that when applying the filter.

Here is my build.gradle

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/INDEX.LIST'
    }
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.famosos.celebrity"
        minSdkVersion 23
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug{
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }

    flavorDimensions "default"
    productFlavors {
        prod {
            dimension "default"
            resValue "string", "app_name", "Famosos"
        }
        dev {
            dimension "default"
            resValue "string", "app_name", "[DEV] Famosos"
        }
        qa {
            dimension "default"
            resValue "string", "app_name", "[QA] Famosos"
        }
        ts {
            dimension "default"
            resValue "string", "app_name", "[TEST] Famosos"
        }

    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:29.2.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.android.support:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-analytics'
}

```

This is where I have located the proguard files:

<img width="279" alt="Captura de Pantalla 2022-09-16 a la(s) 11 43 23 a m" src="https://user-images.githubusercontent.com/47952708/190688709-496d3c95-9ab2-4796-88f0-0bbfb1afc475.png">

And here are the contents of both files:

<img width="770" alt="Captura de Pantalla 2022-09-16 a la(s) 11 45 16 a m" src="https://user-images.githubusercontent.com/47952708/190688912-afa27870-05da-4f10-92a6-c5fb584efa7d.png">

**Comment by J4ckSk3le7on** [comment]
@JoergPf Can we talk and see what settings you used in Android? I still can't get it to work

**Comment by J4ckSk3le7on** [comment]
@wilson-christian Hi, could you please confirm if my code (from the previous comment) is ok, and if not, what should I have?

**Comment by samyakkkk** [comment]
Hi @J4ckSk3le7on , can you please try running from the latest code from the `master.` That should solve the issue of masks not working in android. Please let me know if it doesn't. 

cc @wilson-christian

**Comment by wilson-christian** [comment]
Hi @J4ckSk3le7on can you verify that `0.0.3` has fixed this issue?

**Comment by huutuesn** [comment]
I am facing the same problem. Any effect which requires face detection does not work on Android.

**Comment by samyakkkk** [comment]
@wilson-christian please add this to our task list. Let's review and confirm if it's a bug.

**Comment by wilson-christian** [comment]
Hi @huutuesn @J4ckSk3le7on @JoergPf 
https://docs.deepar.ai/deepar-sdk/deep-ar-sdk-for-android/getting-started#android-12 please configure your app with codes given in the link, that should your issue.

Also please update to our latest version 0.0.4 for better performance.
