### ISSUE TITLE
takeScreenshot() method is very poor 

### ISSUE THREAD

**Issue by AlexXmoe** [DeepARSDK/deepar-flutter-plugin#35]
if i am no wrong, takeScreenshot() method is always saving images to the user storage .
well .. what if user does not want that? 
why there is no property for preventing the images being export to storage !!

**Comment by wilson-christian** [comment]
We have fixed this version `0.0.3` and you will now `takeScreenshot()` method will return `file_path` of the image without storing it phone gallery.
