### ISSUE TITLE
plugin has never ever work in production mode 

### ISSUE THREAD

**Issue by reemXmoe** [DeepARSDK/deepar-flutter-plugin#36]
i have tested the plugin in several devices and they all were crashed once the sdk begin initialize

i am using `0.0.2 `version  

here is the error message

```
 thread.cc:2368] Throwing new exception 'no non-static method "Lai/deepar/ar/DeepAR;.prepareSound(Ljava/lang/String;I[B)V"' with unexpecte
d pending exception: java.lang.NoSuchMethodError: no non-static method "Lai/deepar/ar/DeepAR;.playSound(Ljava/lang/String;IZ)V"
: thread.cc:2368]   at void ai.deepar.ar.DeepAR.initializeAR(java.lang.Object, android.content.res.AssetManager, int, int, android.content.
Context) (SourceFile:-2)
```

**Comment by wilson-christian** [comment]
@reemXmoe can you share `proguard-rules.pro` file content?

**Comment by reemXmoe** [comment]
-keepclassmembers class ai.deepar.ar.DeepAR.** { *; }
-keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava.** { *; }
-keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava.** { *; }
-dontwarn android.**
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

**Comment by reemXmoe** [comment]
```
-keepclassmembers class ai.deepar.ar.DeepAR.** { *; }
-keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava.** { *; }
-keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava.** { *; }
-dontwarn android.**
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; } 
```

**Comment by wilson-christian** [comment]
Update the top 3 rules like below & it should work.

`-keepclassmembers class ai.deepar.ar.DeepAR { *; }
-keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava { *; }
-keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava`

**Comment by wilson-christian** [comment]
```
-keepclassmembers class ai.deepar.ar.DeepAR { *; }
-keepclassmembers class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava { *; }
-keep class ai.deepar.ar.core.videotexture.VideoTextureAndroidJava
```

Update top 3 rules with above & it should work.

**Comment by reemXmoe** [comment]
i had had updated them but when i remove `**` it give me red line with whole line with message error `Unresolved class name`
but when i add `** ` the message error disappear and also the red line 

NOTE : yes it work in release mode thanks but why red line ?

![dd](https://user-images.githubusercontent.com/104551969/194313586-e96a88dc-0340-40eb-be28-6f20a875b4b7.png)

**Comment by skol101** [comment]
IT'd be nice if DeepAR would take more care of this plugin.

**Comment by samyakkkk** [comment]
@reemXmoe since the original production issue is now resolved, closing this issue. Opened a new issue for the red lines.
