### ISSUE TITLE
destroy() method does not work correctly

### ISSUE THREAD

**Issue by sam4523** [DeepARSDK/deepar-flutter-plugin#37]
i am getting the following strange message when i call ` destroy()` method 

`E/Error   (27704): java.lang.IllegalStateException: DeepAR not yet initialized! Can't call this method before the DeepAR is initialized.`

NOTE: Although DeepAR is completely initialized ,but i am getting this error.  i am really totally confused 

i am using `^0.0.2 `version

**Comment by INSPIRATIO** [comment]
Here too. After initializing DeepAR, leaving the current page and using DeepAR again, the same error appears:

`E/Error   (17939): java.lang.IllegalStateException: DeepAR not yet initialized! Can't call this method before the DeepAR is initialized.
W/System.err(17939): java.lang.IllegalStateException: DeepAR not yet initialized! Can't call this method before the DeepAR is initialized.
W/System.err(17939):    at ai.deepar.ar.DeepAR.checkValidState(DeepAR.java:656)
W/System.err(17939):    at ai.deepar.ar.DeepAR.receiveFrame(DeepAR.java:674)
W/System.err(17939):    at com.deepar.ai.CameraXHandler$1$1.analyze(CameraXHandler.java:161)
W/System.err(17939):    at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$androidx-camera-core-ImageAnalysis(ImageAnalysis.java:371)
W/System.err(17939):    at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda0.analyze(Unknown Source:4)
W/System.err(17939):    at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:87)
W/System.err(17939):    at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(17939):    at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(17939):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17939):    at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(17939):    at android.os.Looper.loop(Looper.java:288)
W/System.err(17939):    at android.app.ActivityThread.main(ActivityThread.java:7898)
W/System.err(17939):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(17939):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(17939):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

Flutter version: 3.3.2
DeepAR version: ^0.0.2
Tested on Android 12 & 13

**Comment by wilson-christian** [comment]
Closing this as it is fixed in the latest version `0.0.3`
