### ISSUE TITLE
the size of preview screen differently from the captured images  

### ISSUE THREAD

**Issue by jack84156** [DeepARSDK/deepar-flutter-plugin#39]
Pictures taken by  `.takeScreenshot()` give a completely different size than it was on the display screen

And to be very clear : The difference is in the height of the preview screen, not the size itself.

it seem like the height of the preview screen does not match the Photos returned from `.takeScreenshot()` !!

I am not sure whether this is a bug or poor defect in DeepAr's sdk  quality !!

**Comment by wilson-christian** [comment]
Hi, @jack84156 can you share some examples/images where you are getting different heights?

Side Note: DeepAR SDK will take screenshots on the basis of the resolution for example if you have set 360*640 the method will return an image of the same resolution.

**Comment by jack84156** [comment]
the difference is from  preview screen it's self . 
i tested it in real big phone screens like iphone 13 pro max . the face look funny like is very long face.
that's happen when i give the preview FULL screen .

context : when i give the preview padding from bottom: 50 , it became some better than full screen   

screenshot method gives expected result BUT of course not the same that one in  preview widget 

in other word 
1- i begin aim the camera on me (the face look long )
2- i call screenshot method (result is normal face not long )

**Comment by samyakkkk** [comment]
@jack84156 we are fixing this in #52. Please expect a resolution soon(1-2) days. I am closing this issue here.

**Comment by vividamazilla** [comment]
![image](https://user-images.githubusercontent.com/47826821/201551497-2684539a-104b-43db-ab16-a90b863ab940.png)

is this the same bug?

**Comment by vividamazilla** [comment]
![Screenshot_20221114-075742](https://user-images.githubusercontent.com/47826821/201551560-23dc72e9-92e9-445c-9e2b-746a48ce95b6.jpg)

is this the same bug?
