### ISSUE TITLE
waste of time, totally useless

### ISSUE THREAD

**Issue by bulanni00** [DeepARSDK/deepar-flutter-plugin#40]
Launching lib\main.dart on PGKM10 in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:E:\FlutterApp\deepar_test\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:2: AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'com.30seo.deepar_test'.

     ERROR:E:\FlutterApp\deepar_test\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:34: AAPT: error: attribute 'android:name' in <activity> tag must be a valid Java class name.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by jack84156** [comment]
you are in better case , you will have too mush of bugs after .. i hope this plugin get seriously update

**Comment by samyakkkk** [comment]
@bulanni00 this seems to be an error with your AndroidManifest.xml file. `error: attribute 'android:name' in <activity> tag must be a valid Java class name`. Check this [SO](https://stackoverflow.com/a/55611819/13038101). 

I am closing this issue. If you think, it is a problem with our end, please let us know and we will help you ASAP. Thanks!
