### ISSUE TITLE
Camera remains active after destroying DeepAR

### ISSUE THREAD

**Issue by tobtraa** [DeepARSDK/deepar-flutter-plugin#41]
Additionally to this issue: https://github.com/DeepARSDK/deepar-flutter-plugin/issues/38#issue-1383185135 the camera remains active.

**Comment by Mohammad-AlZabibi** [comment]
Same as here, and getting this error after calling destroy :


E/libEGL  ( 8456): eglDestroySurfaceImpl:844 error 300d (EGL_BAD_SURFACE)
W/System.err( 8456): java.lang.IllegalStateException: DeepAR not yet initialized! Can't call this method before the DeepAR is initialized.
W/System.err( 8456): 	at ai.deepar.ar.DeepAR.checkValidState(DeepAR.java:656)
W/System.err( 8456): 	at ai.deepar.ar.DeepAR.receiveFrame(DeepAR.java:674)
W/System.err( 8456): 	at com.deepar.ai.CameraXHandler$1$1.analyze(CameraXHandler.java:161)
W/System.err( 8456): 	at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:371)
W/System.err( 8456): 	at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
W/System.err( 8456): 	at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer

**Comment by wilson-christian** [comment]
fixed in `0.0.3`
