### ISSUE TITLE
use my Effects that i created

### ISSUE THREAD

**Issue by aouees** [DeepARSDK/deepar-flutter-plugin#47]
i just export my effect from DeepAR Studio and add the file *.deepar to my project assets .. but it don't work 
no error  or exception found .. just it's don't  work 
i use flutter with deepar_flutter 0.0.2

**Comment by aouees** [comment]
Thank @tobsnti  for answering my question ..
I don't know how to use 'switchEffectWithSlot' ... what Slot parmeter mean in this function ??

**Comment by tobsnti** [comment]
@aouees the slot parameter is just a string where you can define a slot that is being used to apply the filter, i.e. you can use 'mask'.

**Comment by aouees** [comment]
@tobsnti thanks you  ... i try it .. but not work .. i write print statements  befor and after switch effect statement .. the app print befor . But after no response..

**Comment by wilson-christian** [comment]
Hi @aouees we have updated the plugin to `0.0.3` it should fix your issue, please try it out & let us know if the issue still persists.
