### ISSUE TITLE
Can't use switchEffect from non-asset directory

### ISSUE THREAD

**Issue by tobsnti** [DeepARSDK/deepar-flutter-plugin#48]
**How to reproduce:**
On an iOS device(Android not checked) download an asset i.e. via Dio.download(), file is located i.e. under '/var/mobile/Containers/Data/Application/59658325-6433-44C5-AC78-7B0F32573EE0/Documents/cheddar/mask/aviators', the function switchEffect() can't load this asset to apply the effect.

**Diagnose:**
I think DeepArCamera.swift holds the "bug" in this part:
`        case "switch_effect":
            let effect:String = args?["effect"] as! String
            let key = registrar?.lookupKey(forAsset: effect)
            let path = Bundle.main.path(forResource: key, ofType: nil)
            deepAR.switchEffect(withSlot: "effect", path: path)`
Only registered assets are bein loaded.

**Why it is needed:**
In our application it is possible to upload and use different AR-Filters in multiple 'campaigns', so we need to be fully dynamic, download the filters on runtime and use them.

**Current workaround:**
The function switchEffectWithSlot() is able to load assets located in the Application Documents Directory.

**EDIT:**
This also occurs with switchMask() and switchFilter()

**Comment by jack84156** [comment]
did you try to load them using other function , like .switchMask() or  .switchFilter() ?

**Comment by tobsnti** [comment]
@jack84156 thank you for the feedback, these functions are also only loading registered assets, I already edited the issue.
As you can read in the section "Current workaround:" does it work with switchEffectWithSlot().

**Comment by jack84156** [comment]
do you accept other complicated ways for making it work ?

**Comment by jack84156** [comment]
i am not sure if it will suit with your case use , but here what i have done , and i am happy with that .

1- Create an integrated function that runs at the start of the application
2- Import all the required filters from your server and store them in `shared_preferences` 

Through the previous two steps, you have the ability to update or change the filters every time you start your application.

Now : feel free to convert any data that you already stored them into `shared_preferences`  TO assets path. There are a lot of ways to do that .

context : Through this process, you will deal with any filter as `assets` . also all of it will be done in one function that i mentioned .

**Comment by Anas-mo101** [comment]
@jack84156 could you provide more details on the `shared_preferences` method you mentioned.

I'm trying to achieve a very similar goal to @tobsnti , but `switchEffectWithSlot()` function does not load non-assets effects as I tried to load it from Document Directory.

**Comment by rlee1990** [comment]
Can someone please provide more details on this?
@tobsnti @jack84156
