### ISSUE TITLE
Preview widget is stretched. 

### ISSUE THREAD

**Issue by samyakkkk** [DeepARSDK/deepar-flutter-plugin#52]

**Comment by samyakkkk** [comment]
Created in lieu of #39.

**Comment by Alexd3VAoe** [comment]
@samyakkkk Has this problem been fixed?

**Comment by samyakkkk** [comment]
@Alexd3VAoe it has been fixed in `dev`. We will be releasing it soon.

**Comment by wilson-christian** [comment]
fixed in `0.0.3`
