### ISSUE TITLE
Proguard rules give red lines

### ISSUE THREAD

**Issue by samyakkkk** [DeepARSDK/deepar-flutter-plugin#56]
i had had updated them but when i remove `**` it give me red line with whole line with message error `Unresolved class name`
but when i add `** ` the message error disappear and also the red line 

NOTE : yes it work in release mode thanks but why red line ?

![dd](https://user-images.githubusercontent.com/104551969/194313586-e96a88dc-0340-40eb-be28-6f20a875b4b7.png)

_Originally posted by @reemXmoe in https://github.com/DeepARSDK/deepar-flutter-plugin/issues/36#issuecomment-1269962328_

**Comment by wilson-christian** [comment]
@reemXmoe are you still facing this issue? Can you try to clean the cache & restart it? Seems to be a local machine issue.
