### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by bukenyajose** [DeepARSDK/deepar-flutter-plugin#57]
```
Flutter 3.3.2
```

**Comment by samyakkkk** [comment]
@wilson-christian please take a look. thanks for reporting @bukenyajose.

**Comment by bukenyajose** [comment]
Very excited to see this working

**Comment by wilson-christian** [comment]
@bukenyajose can you share some more details, please?

**Comment by bukenyajose** [comment]
@samyakkkk @wilson-christian Thanks for your positive response. Actually version`0.0.3` resolved this issue with the filters but now masks aren't working yet and the preview doesn't fit the screen

**Comment by samyakkkk** [comment]
@bukenyajose regarding preview please check this [resolution](https://github.com/DeepARSDK/deepar-flutter-plugin/issues/61#issuecomment-1331683622).

Can you please share more details on **masks aren't working.**

**Comment by wilson-christian** [comment]
https://docs.deepar.ai/deepar-sdk/deep-ar-sdk-for-android/getting-started#android-12

@bukenyajose please checkout the above link & add config to load masks correctly. That should solve the issue, if it re-appears please feel free to comment here.
