### ISSUE TITLE
issue in 0.0.3 version related full screen 

### ISSUE THREAD

**Issue by Alexd3VAoe** [DeepARSDK/deepar-flutter-plugin#61]
the stretched issue is fixed but preview widget wont be in full screen at all 

i have tried  with following 

```
1- DeepArPreview(deepArController)


2-     final size = MediaQuery.of(context).size;
        final deviceRatio = size.width / size.height;
        Transform.scale(
                scale: (1 / deepArController.aspectRatio) / deviceRatio,
                child: DeepArPreview(deepArController)
            )




3-      AspectRatio(
          aspectRatio: (1 / deepArController.aspectRatio),
          child: DeepArPreview(deepArController)


```

i have used the whole previous codes but they all gave like 100 px padding from button like following 

 
![111](https://user-images.githubusercontent.com/116365233/202161591-ae8d658f-505a-4a53-aa59-b4f299b812b6.png)

i am using real device .. Redmi 9 (big screen)

**Comment by Alexd3VAoe** [comment]
@wilson-christian ANY UPDATE ??

**Comment by samyakkkk** [comment]
@Alexd3VAoe We are looking into it.

**Comment by skol101** [comment]
Please, update @samyakkkk

**Comment by samyakkkk** [comment]
@skol101 @Alexd3VAoe This isn't an issue related to the plugin but rather to the implementation on the app side.

The `deviceRatio` from `MediaQuery` isn't the exact size we are rendering our camera preview on but is the size of the complete app window including the status bar and app bar sizing. 

I would recommend first finding out the size of the widget that needs to be covered and using that ratio in the transform.

```
  return Scaffold(
        body: Stack(
      children: [
        SizedBox.expand(
          key: key,
          child: Center(
            child: Transform.scale(
              scale: scaleFactor,
              child: DeepArPreview(
                _controller,
                onViewCreated: () {
                  WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
                    final renderBox = key.currentContext?.findRenderObject();
                    final size = (renderBox as RenderBox).size;
                    setState(() {
                      scaleFactor =
                          size.height / (size.width * _controller.aspectRatio);
                    });
                  });
                },
              ),
            ),
          ),
        ),
        _topMediaOptions(),
        _bottomMediaOptions(),
      ],
    ));
```

**Comment by Alexd3VAoe** [comment]
@samyakkkk thanks for your expiation .. It should not be assumed by the user ,especially since what you said is not true enough .
There are lots and lots of plugins like (Camera plugin) that already comes to fit any device full screen ! 
I didn't understand why so much complexity at such a simple point . 
Note : it is easy for anyone to make it in full screen but the stretched issue occurs so there are wrong measurements from the plugin itself that prevent anyone to have full screen without  stretched issue
and yeah by the way what you have done recently to solve the  stretched issue shrinking the screen size is not a solution to the stretched issue its self

i can remember i have done it my self by  shrinking the screen size to avoid stretched issue but (no full screen)  . but now The process is reversed i have done the full screen issue but (stretched issue again)
I think this is a technical weakness . I really hope you guys fix the problem because this is the only thing keeping me from getting started in production mode 


thanks

**Comment by samyakkkk** [comment]
@Alexd3VAoe The issue has been fixed and is available in `dev`. Will be released in the next version.
