### ISSUE TITLE
i'm getting these notes which i didn'nt understand: 

### ISSUE THREAD

**Issue by Hassen-Elmahrouk** [DeepARSDK/deepar-flutter-plugin#62]

**Comment by Hassen-Elmahrouk** [comment]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\deepar_flutter-0.0.3\android\src\main\java\com\deepar\ai\CameraXHandler.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\deepar_flutter-0.0.3\android\src\main\java\com\deepar\ai\DeepArPlugin.java uses unchecked or unsafe operations.

**Comment by wilson-christian** [comment]
Hi @Hassen-Elmahrouk these are warnings. Did you get an error? was the app not able to build?

**Comment by wilson-christian** [comment]
Please update to our latest version `0.0.4` to fix this issue. @Hassen-Elmahrouk
