### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by alkaou** [DeepARSDK/deepar-flutter-plugin#64]
Hello everyone, I just spent a whole day implementing DeepAR in my flutter application, I followed all your instructions but still got errors. Can you help me please. I will be very happy.

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform deepar-.aar (:deepar:) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar.
         > /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar/AndroidManifest.xml
   > Failed to transform deepar-.aar (:deepar:) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=integration}.
      > Execution failed for AarResourcesCompilerTransform: /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar.
         > /home/alkaou/.gradle/caches/transforms-3/42a82e61580fc66ffbe345bcaf1f93f9/transformed/jetified-deepar/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s
Running Gradle task 'assembleDebug'...                            137,0s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by wilson-christian** [comment]
Hi @alkaou are you trying to run on simulator or real device?

**Comment by wilson-christian** [comment]
Please update to our latest version `0.0.4` to fix this issue. @alkaou
