### ISSUE TITLE
effect doesn't work perfectly

### ISSUE THREAD

**Issue by rifathossain82** [DeepARSDK/deepar-flutter-plugin#65]
### Please help me to solve this problem. I don't see any problem but the effect doesn't work. I can't see my face.

![Screenshot_20230102-170326](https://user-images.githubusercontent.com/88751768/210223842-0124b611-603a-44a2-aee7-b7a752fe5cc4.png)
![Screenshot (42)](https://user-images.githubusercontent.com/88751768/210223872-3733ec5f-44a3-4f4a-8c8d-15d630c40cf3.png)
![Screenshot (41)](https://user-images.githubusercontent.com/88751768/210223882-0dc644c7-a9bf-489a-9211-caef0f98fc12.png)

**Comment by huutuesn** [comment]
I have the same problem. All effect which requires face do not work (no face shown).
It may be related to this issue https://github.com/DeepARSDK/deepar-flutter-plugin/issues/28.

This team does not provide any support.

**Comment by wilson-christian** [comment]
Hi, @rifathossain82 @huutuesn can you provide your testing device config, please?

**Comment by huutuesn** [comment]
@wilson-christian I am using Vivo 2015-Y1s

**Comment by huutuesn** [comment]
Team, any update???

**Comment by wilson-christian** [comment]
@huutuesn this issue currently is in testing & once verified we will revert.

**Comment by wilson-christian** [comment]
Please configure your app according to : https://docs.deepar.ai/deepar-sdk/deep-ar-sdk-for-android/getting-started#android-12 this should fix the issue.

@huutuesn @rifathossain82

**Comment by huutuesn** [comment]
@wilson-christian it does not help!! I have tried even before your comment.
Btw, my device runs on Android 10. It should not relate to your comment which applies for Android 12.

Please investigate CAREFULLY and provide the detail correction/instructions.

See the image. 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/4954278/215305409-38500bbc-d267-48cc-8457-5dd8ca57d5ea.png">
